---
## Change the name of the resource
## Default: use the chart name
# nameOverride:

## The image to use with the resource
## Ref: https://quay.io/repository/littlemanco/apache-php
image:

# securityContext:
## Whether the container should be run in "Privileged" mode (essentially, root on the host)
## Ref: http://kubernetes.io/docs/api-reference/v1/definitions/#_v1_securitycontext
## Default: false
#  privileged:

service:
  ## What scope the service should be exposed in. One of:
  ## - LoadBalancer (to the world)
  ## - ClusterIP (to the cluster)
  ## - NodePort (to the world, in a custom way)
  type: "LoadBalancer"
  ## If there is a particular IP that should be used for the service, specify it here.
  ## Note: It's quite unlikely that an IP should be specific. Normally, the best thing to do is leave it to Kubernetes
  ##       to allocate a free IP from the pool.
  ## Default: Automatically assign a random IP
  # privateIp:
  ## Only relevant if the `type` above is "LoadBalancer"
  loadBalancer:
    ## If there is already a reserved public IP that this load balancer should use, indicate it here.
    ## Default: Automatically assign a random, ephemeral IP
    # publicIp:
    ## If there should be firewall rules restricting the load balancer to a limited set of IPs, specify those IPs below
    ## in CIDR format. If all IPs shoud be allowed access, set the CIDR as "0.0.0.0/0"
    allowedIps:
      - "0.0.0.0/0"

## How many versions of this service to run on kubernetes
replicas: 1

## Ref: http://kubernetes.io/docs/user-guide/compute-resources/
## Ref: https://github.com/kubernetes/kubernetes/blob/master/docs/design/resource-qos.md
## Ref: https://docs.docker.com/engine/reference/run/#/runtime-constraints-on-resources
resources:
  requests:
    ## How much CPU this container is expected to need
    cpu: 100m
    ## How much memory this container is expected to need
    memory: 512Mi
  limits:
    ## The max CPU this container should be allowed to use
    cpu: 100m
    ## The max memory this container should be allowed to use. Note: If a container exceeds its memory limit, 
    ## it may terminated.
    memory: 512Mi

monitoring:
  scrape:
    ## Whether to scrape this service with the montoring toolkit. Service must expose metrics in the prometheus format.
    service: false
